# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bazzite-gaming
description: Custom Bazzite gaming image with all essential tools
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - rmnscnce/ulauncher  # для Ulauncher если нужно
    install:
      packages:
        # Системные утилиты
        - git
        - curl
        - wget
        - htop
        - neovim
        - fastfetch  # современная замена neofetch
        - zsh        # мощная оболочка с автодополнением
        - starship   # красивое приглашение командной строки
        
        # Игровое железо AMD
        - rocm-hip-sdk
        - rocm-opencl-sdk
        
        # Медиа и графика
        - ffmpeg
        - gstreamer1-plugins-ugly
        - gstreamer1-plugins-bad-free
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # Браузеры
          - com.brave.Browser
          - com.microsoft.Edge
          
          # Игры и игровые сервисы
          - com.valvesoftware.Steam
          - com.heroicgameslauncher.hgl
          - net.lutris.Lutris
          
          # Медиа - ВСЁ В ОДНОМ
          - io.github.celluloid_player.Celluloid  # видео (лучший для GNOME)
          - org.gnome.Loupe                      # изображения

          # Коммуникации
          - com.rambox.Rambox
    
          
          # Утилиты
          - org.gnome.Screenshot  # аналог Spectacle для GNOME
          - com.github.tchx84.Flatseal

   
      - scope: user

  - type: script
    shippets:
      # Установка Ollama
      - |-
        curl -fsSL https://ollama.ai/install.sh | sh
      
      # Настройка Zsh как оболочки по умолчанию
      - |-
        chsh -s $(which zsh)
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
