# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: template
description: HUES-OS v1.2 - Stable Fedora 41 + Hyprland
base-image: ghcr.io/ublue-os/kinoite-main
# ВАЖНО: Версия 41 - стабильная. На ней есть Hyprland и все пакеты.
# Latest (43) сейчас сломана для Hyprland.
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Подключаем RPM Fusion (для драйверов NVIDIA и кодеков)
  - type: bling
    install:
      - rpmfusion

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  - type: dnf
    install:
      packages:
        # --- HYPRLAND STACK ---
        # В Fedora 41 эти пакеты есть и работают стабильно
        - hyprland
        - waybar
        - wofi
        - swaybg
        - swaylock
        - swayidle
        - mako
        - xdg-desktop-portal-hyprland
        
        # --- ИНСТРУМЕНТЫ WAYLAND ---
        - grim
        - slurp
        - wl-clipboard
        
        # --- КОНСОЛЬНЫЕ УТИЛИТЫ ---
        - fastfetch
        - starship
        - zoxide
        - eza
        - fzf
        - bat

    # Удаляем системный Firefox, так как ставим его через Flatpak
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # --- ИГРЫ (Gamemode и Steam-devices подтянутся автоматически или поставишь вручную) ---
          - com.valvesoftware.Steam
          - net.lutris.Lutris
          - com.heroicgameslauncher.hgl
          - com.usebottles.bottles
          
          # --- ОБЩЕНИЕ ---
          - dev.vencord.Vesktop
          - org.telegram.desktop
          
          # --- МЕДИА (MPV здесь работает идеально со всеми кодеками) ---
          - io.mpv.Mpv
          - org.kde.haruna
          - com.obsproject.Studio
          - org.kde.gwenview
          
          # --- БРАУЗЕРЫ ---
          - com.brave.Browser
          - com.microsoft.Edge
          - org.mozilla.firefox
          
          # --- СИСТЕМНЫЕ УТИЛИТЫ ---
          - com.github.tchx84.Flatseal
          - org.kde.ark
          - org.kde.filelight
          - io.github.flattool.Warehouse
