# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: template
description: HUES-OS v1.2 - KDE + Hyprland Gaming Beast
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Шрифты (КРИТИЧЕСКИ ВАЖНЫ ДЛЯ HYPRLAND и Waybar)
- type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  - type: dnf
    repos:
      copr:
        - atim/starship
        - solopasha/hyprland # Свежий Hyprland (опционально, но лучше иметь свежий)
 
    install:
      packages:
        # --- CORE UTILS ---
        - git
        - curl
        - wget
        - htop
        - neovim
        - fastfetch
        - zsh
        - starship
        - zoxide
        - bat
        - eza
        - fzf
        - thefuck
        
        # --- HYPRLAND BASE (Добавляем базу Гиперлэнда) ---
        - hyprland          # Сам оконный менеджер
        - waybar            # Верхняя панель (база для Hyprland)
        - wofi              # Меню запуска приложений (аналог "Пуск")
        - swaybg            # Для установки обоев
        - swaylock          # Экран блокировки
        - swayidle          # Управление простоем (сон)
        - mako              # Уведомления
        - kitty             # Терминал (лучший для Hyprland)
        - polkit-kde        # Агент авторизации (чтобы пароль спрашивал)
        - qt5-qtwayland     # Чтобы Qt приложения работали в Wayland
        - qt6-qtwayland
        - xdg-desktop-portal-hyprland # Для записи экрана и шаринга
        - grim              # Скриншоты
        - slurp             # Выделение области скриншота
        - wl-clipboard      # Работа буфера обмена
        
        # --- GAMING & DRIVERS ---
        - rocm-hip
        - rocm-opencl
        - mpv
        - partitionmanager
        
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # --- BROWSERS ---
          - com.brave.Browser
          - com.microsoft.Edge
          
          # --- GAMING ---
          - com.valvesoftware.Steam
          - net.lutris.Lutris
          - com.heroicgameslauncher.hgl
          - net.davidotek.pupgui2    # ProtonUp-Qt
          - io.github.ben24.goverlay # MangoHud config
          - com.usebottles.bottles
          
          # --- SOCIAL ---
          - org.telegram.desktop
          - dev.vencord.Vesktop      # Discord
          
          # --- MEDIA ---
          - org.kde.haruna
          - org.kde.gwenview
          - com.obsproject.Studio
          
          # --- SYSTEM ---
          - com.github.tchx84.Flatseal
          - org.kde.ark
          - org.kde.filelight
          - io.github.flattool.Warehouse # ВОТ ЭТА ШТУКА ПОМОЖЕТ УПРАВЛЯТЬ ФЛАТПАКАМИ

      - scope: user
