# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: template
description: HUES-OS v1.2 - Pure Fedora Kinoite + Hyprland
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Исправление: просто указываем тип, настройки по умолчанию поставят free и nonfree
  - type: rpm-fusion

  - type: fonts
    fonts:
    # ... (далее ваш код без изменений)

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  - type: dnf
    repos:
      copr:
        - solopasha/hyprland
 
    install:
      packages:
        # --- БАЗА ДЛЯ ИГР И МЕДИА (Чего нет в чистой Федоре) ---
        - ffmpeg
        - gstreamer1-plugin-openh264
        - gstreamer1-plugins-bad-free
        - gstreamer1-plugins-ugly-free
        - steam-devices       # Чтобы работали геймпады
        - gamemode            # Оптимизация игр
        
        # --- HYPRLAND STACK ---
        - hyprland
        - waybar
        - wofi
        - swaybg
        - swaylock
        - swayidle
        - mako
        - kitty
        - xdg-desktop-portal-hyprland
        - grim
        - slurp
        - wl-clipboard
        
        # --- УТИЛИТЫ ---
        - mpv
        - fastfetch
        - starship
        - zoxide
        - bat
        - eza
        - fzf
        # thefuck лучше ставить через brew, в dnf он часто ломает python

    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # --- BROWSERS ---
          - com.brave.Browser
          - com.microsoft.Edge
          
          # --- GAMING ---
          - com.valvesoftware.Steam
          - net.lutris.Lutris
          - com.heroicgameslauncher.hgl
          - net.davidotek.pupgui2
          - com.usebottles.bottles
          
          # --- SOCIAL ---
          - org.telegram.desktop
          - dev.vencord.Vesktop
          
          # --- MEDIA ---
          - org.kde.haruna
          - org.kde.gwenview
          - com.obsproject.Studio
          
          # --- SYSTEM ---
          - com.github.tchx84.Flatseal
          - org.kde.ark
          - org.kde.filelight
          - io.github.flattool.Warehouse

      - scope: user
