# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: template
description: HUES-OS v1.1 - KDE + Hyprland Gaming Beast
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  - type: dnf
    repos:
      copr:
        # ВЕРНУЛИ ЕГО, так как без него Hyprland не находится
        - solopasha/hyprland
 
    install:
      packages:
        # --- HYPRLAND CORE ---
        - hyprland
        - waybar
        - wofi
        - swaybg
        - swaylock
        - swayidle
        - mako
        - kitty
        # xdg-desktop-portal-hyprland тоже может конфликтовать, 
        # но пока оставим. Если упадет - удалим.
        - xdg-desktop-portal-hyprland 
        
        # --- УБРАЛИ КОНФЛИКТНЫЕ ---
        # - wl-clipboard (Уже есть в Bazzite!)
        # - grim (Уже есть!)
        # - slurp (Уже есть!)
        # - thefuck (Конфликтует с Python)
        
        # --- МЕДИА ---
        - mpv

    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # --- BROWSERS ---
          - com.brave.Browser
          - com.microsoft.Edge
          
          # --- GAMING ---
          - com.valvesoftware.Steam
          - net.lutris.Lutris
          - com.heroicgameslauncher.hgl
          - net.davidotek.pupgui2
          - io.github.ben24.goverlay
          - com.usebottles.bottles
          
          # --- SOCIAL ---
          - org.telegram.desktop
          - dev.vencord.Vesktop
          
          # --- MEDIA ---
          - org.kde.haruna
          - org.kde.gwenview
          - com.obsproject.Studio
          
          # --- SYSTEM ---
          - com.github.tchx84.Flatseal
          - org.kde.ark
          - org.kde.filelight
          - io.github.flattool.Warehouse

      - scope: user
