# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: template
description: HUES-OS v1.2 - Pure Fedora Kinoite + Hyprland
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # 1. Подключаем репозитории
  - type: bling
    install:
      - rpmfusion

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  # 2. Этап первый: Утилиты (Самые безопасные пакеты)
  - type: dnf
    install:
      packages:
        - fastfetch
        - starship
        - zoxide
        - bat
        - eza
        - fzf
        - gamemode
        - grim
        - slurp
        - wl-clipboard

  # 3. Этап второй: Hyprland (Самые сложные пакеты)
  # Если сборка упадет здесь, мы будем знать, что проблема именно в Hyprland
  - type: dnf
    install:
      packages:
        - hyprland
        - waybar
        - wofi
        - swaybg
        - swaylock
        - swayidle
        - mako
        - xdg-desktop-portal-hyprland
        # - steam-devices # Временно отключено, часто ломает сборку

  # Удаление пакетов вынесли отдельно, чтобы не мешать установке
  # Если здесь будет ошибка, закомментируйте этот блок
  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # --- ПЕРЕНЕСЕНО ИЗ DNF (Так надежнее) ---
          - io.mpv.Mpv           # MPV лучше работает из Flatpak (кодеки включены)
          - org.mozilla.firefox  # Возвращаем Firefox, но уже как Flatpak
          
          # --- TERMINAL ---
          # Kitty сложно собирается в слоях, через Flatpak безопаснее, 
          # либо используйте Ptyxis (родной для Fedora)
          # Если очень нужен нативный Kitty, верните его в DNF, но MPV точно оставьте тут.
          
          # --- BROWSERS ---
          - com.brave.Browser
          - com.microsoft.Edge
          
          # --- GAMING ---
          - com.valvesoftware.Steam
          - net.lutris.Lutris
          - com.heroicgameslauncher.hgl
          - net.davidotek.pupgui2
          - com.usebottles.bottles
          
          # --- SOCIAL ---
          - org.telegram.desktop
          - dev.vencord.Vesktop
          
          # --- MEDIA ---
          - org.kde.haruna
          - org.kde.gwenview
          - com.obsproject.Studio
          
          # --- SYSTEM ---
          - com.github.tchx84.Flatseal
          - org.kde.ark
          - org.kde.filelight
          - io.github.flattool.Warehouse
