# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: HUES-OS-os
description: Custom Bazzite gaming image with all essential tools
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
 
    install:
      packages:
        # Системные утилиты
        - git
        - curl
        - wget
        - htop
        - neovim
        - fastfetch  # современная замена neofetch
        - zsh        # мощная оболочка с автодополнением
        - starship   # красивое приглашение командной строки
        
        # Игровое железо AMD
        - rocm-hip
        - rocm-opencl
        
        # Медиа и графика
        
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # Браузеры
          - com.brave.Browser
          - com.microsoft.Edge
          
          # Игры и игровые сервисы
          - com.valvesoftware.Steam
          - com.heroicgameslauncher.hgl
          - net.lutris.Lutris
          
          # Медиа - ВСЁ В ОДНОМ
          - io.github.celluloid_player.Celluloid  # видео (лучший для GNOME)
          - org.gnome.Loupe                      # изображения

          # Коммуникации
       
    image:
     formats:
      - iso
          
          # Утилиты
            # аналог Spectacle для GNOME
          - com.github.tchx84.Flatseal

   
      - scope: user


