# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: template
description: HUES-OS v1.2 - Stable Fedora 41 + Hyprland (Clean Build)
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  # RPM Fusion оставляем (драйверы AMD и кодеки будут доступны)
  - type: bling
    install:
      - rpmfusion

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  - type: dnf
    install:
      packages:
        # --- HYPRLAND CORE (Самое важное) ---
        - hyprland
        - cliphist
        - gamemode
        -topgrade
        - waybar
        - wofi
        - swaybg
        - swaylock
        - swayidle
        - mako
        - xdg-desktop-portal-hyprland
        
        # --- ИНСТРУМЕНТЫ ---
        - grim
        - slurp
        # - wl-clipboard  <-- УДАЛЕНО: Уже есть в системе
        
        # --- УТИЛИТЫ ---
        - fastfetch
        - bat
        - zoxide
        # - starship      <-- УДАЛЕНО: Вызывало ошибку поиска, поставишь вручную
        # - eza           <-- УДАЛЕНО: Вызывало ошибку
        # - fzf           <-- УДАЛЕНО: Уже есть в системе

    # Удаление Firefox иногда вызывает проблемы зависимостей, 
    # временно закомментируем, чтобы точно собрать образ.
    # remove:
    #   packages:
    #     - firefox

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # --- ИГРЫ ---
          - com.valvesoftware.Steam
          - net.lutris.Lutris
          - com.heroicgameslauncher.hgl
          - com.usebottles.bottles
          
          # --- ОБЩЕНИЕ ---
          - dev.vencord.Vesktop
          - org.telegram.desktop
          
          # --- МЕДИА ---
          - io.mpv.Mpv
          - org.kde.haruna
          - com.obsproject.Studio
          - org.kde.gwenview
          
          # --- БРАУЗЕРЫ ---
          - com.brave.Browser
          - com.microsoft.Edge
          - org.mozilla.firefox
          
          # --- СИСТЕМА ---
          - com.github.tchx84.Flatseal
          - org.kde.ark
          - org.kde.filelight
          - io.github.flattool.Warehouse
