# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json  
name: hues-os
description: HUES-OS v1.2 - Stable Fedora 41 + Hyprland + AI Core
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 41

modules:
  # 1. Копируем файлы (твои скрипты hues-ai и конфиги)
  - type: files
    files:
      - source: system
        destination: /

  # 2. Подключаем RPM Fusion и устанавливаем Just
  - type: script
    snippets:
      - dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      - dnf install -y just

  # 3. Включаем COPR репозитории
  - type: script
    snippets:
      - dnf -y copr enable solopasha/hyprland
      - dnf -y copr enable atim/topgrade

  # 4. Шрифты
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  # 5. Установка пакетов
  - type: dnf
    install:
      packages:
        # --- HYPRLAND CORE ---
        - hyprland
        - waybar
        - wofi
        - swaybg
        - mako
        - xdg-desktop-portal-hyprland
        - hyprlock
        - hypridle

        # --- ЗАВИСИМОСТИ ДЛЯ СКРИПТОВ ---
        - gum
        - jq
        - libnotify
        - wl-clipboard
        - cliphist
        
        # --- ИНСТРУМЕНТЫ ---
        - grim
        - slurp
        - udiskie
        - polkit-gnome
        - nwg-look
        - qt5ct
        - qt6ct
        
        # --- CLI ---
        - fastfetch
        - bat
        - zoxide
        - topgrade
        - ripgrep
        - kitty
        - ollama

  # 6. Flatpak приложения
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.valvesoftware.Steam
          - net.lutris.Lutris
          - com.heroicgameslauncher.hgl
          - com.usebottles.bottles
          - dev.vencord.Vesktop
          - org.telegram.desktop
          - io.mpv.Mpv
          - org.kde.haruna
          - com.obsproject.Studio
          - org.kde.gwenview
          - com.brave.Browser
          - com.microsoft.Edge
          - org.mozilla.firefox
          - com.github.tchx84.Flatseal
          - org.kde.ark
          - org.kde.filelight
          - io.github.flattool.Warehouse
          - io.github.mkiol.BoxBuddy

  # 7. ФИНАЛЬНЫЙ ШТРИХ: Делаем скрипты исполняемыми
  - type: script
    snippets:
      - chmod +x /usr/bin/hues-*
