# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: template
description: HUES-OS v1.2 - Pure Fedora Kinoite + Hyprland
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Подключаем репозитории (нужны для драйверов NVIDIA и прочего)
  - type: bling
    install:
      - rpmfusion

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  - type: dnf
    install:
      packages:
        # --- HYPRLAND STACK (База) ---
        - hyprland
        - waybar
        - wofi
        - swaybg
        - swaylock
        - swayidle
        - mako
        - xdg-desktop-portal-hyprland
        
        # --- ВАЖНЫЕ ИНСТРУМЕНТЫ WAYLAND ---
        - grim          # Скриншоты
        - slurp         # Выделение области
        - wl-clipboard  # Буфер обмена
        
        # --- УТИЛИТЫ КОНСОЛИ ---
        - fastfetch
        - starship
        - zoxide
        - eza
        - fzf
        - bat

    # Временно не удаляем Firefox, чтобы не злить установщик
    # remove:
    #   packages:
    #     - firefox

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # --- ГЛАВНОЕ: ИГРЫ И СОЦСЕТИ (Все тут, все будет работать) ---
          - com.valvesoftware.Steam
          - net.lutris.Lutris
          - com.heroicgameslauncher.hgl
          - com.usebottles.bottles
          - dev.vencord.Vesktop         # Твой Дискорд
          - org.telegram.desktop
          
          # --- МЕДИА (MPV тут, чтобы не ломать систему) ---
          - io.mpv.Mpv
          - org.kde.haruna
          - com.obsproject.Studio
          - org.kde.gwenview
          
          # --- БРАУЗЕРЫ ---
          - com.brave.Browser
          - com.microsoft.Edge
          - org.mozilla.firefox
          
          # --- СИСТЕМНЫЕ УТИЛИТЫ ---
          - com.github.tchx84.Flatseal  # Обязательно для настройки прав
          - org.kde.ark
          - org.kde.filelight
          - io.github.flattool.Warehouse
