# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: template
description: HUES-OS v1.2 - Pure Fedora Kinoite + Hyprland
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # RPM Fusion нужен для Steam и драйверов, оставляем
  - type: bling
    install:
      - rpmfusion

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  - type: dnf
    install:
      packages:
        # --- ВРЕМЕННО ОТКЛЮЧЕНО (Поиск источника ошибки) ---
        # Эти пакеты чаще всего вызывают конфликты версий с базой Fedora
        # - libavcodec-freeworld
        # - gstreamer1-plugin-openh264
        # - gstreamer1-plugins-bad-free
        # - gstreamer1-plugins-ugly-free
        
        # --- ИГРЫ ---
        # steam-devices иногда требует non-free репо, который может не успеть прогрузиться.
        # Если сборка пройдет, попробуем включить его обратно.
        # - steam-devices
        - gamemode
        
        # --- HYPRLAND STACK ---
        - hyprland
        - waybar
        - wofi
        - swaybg
        - swaylock
        - swayidle
        - mako
        - kitty
        - xdg-desktop-portal-hyprland
        - grim
        - slurp
        - wl-clipboard
        
        # --- УТИЛИТЫ ---
        - mpv
        - fastfetch
        - starship
        - zoxide
        - bat
        - eza
        - fzf

    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # --- BROWSERS ---
          - com.brave.Browser
          - com.microsoft.Edge
          
          # --- GAMING ---
          - com.valvesoftware.Steam
          - net.lutris.Lutris
          - com.heroicgameslauncher.hgl
          - net.davidotek.pupgui2
          - com.usebottles.bottles
          
          # --- SOCIAL ---
          - org.telegram.desktop
          - dev.vencord.Vesktop
          
          # --- MEDIA ---
          - org.kde.haruna
          - org.kde.gwenview
          - com.obsproject.Studio
          
          # --- SYSTEM ---
          - com.github.tchx84.Flatseal
          - org.kde.ark
          - org.kde.filelight
          - io.github.flattool.Warehouse
