# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: hues-os
description: HUES-OS v1.2 - Stable Fedora 41 + Hyprland + AI Core
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 41

modules:
  # 1. Копируем твои скрипты (hues-ai, hues-startup и др.)
  - type: files
    files:
      - source: system
        destination: /

  # 2. RPM Fusion (Драйверы и кодеки)
  - type: bling
    install:
      - rpmfusion
      - ublue-os-just # Полезные команды обслуживания

  # 3. Шрифты (Нужны для красивого терминала и Waybar)
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  # 4. Дополнительные репозитории (COPR)
  # ВАЖНО: Отступы должны быть ровными!
  - type: copr
    repos:
      - solopasha/hyprland  # Hyprland, cliphist, hyprlock, hypridle
      - atim/topgrade       # Утилита topgrade

  # 5. Основной список пакетов
  - type: dnf
    install:
      packages:
        # --- HYPRLAND CORE ---
        - hyprland
        - waybar
        - wofi
        - swaybg
        - mako                # Уведомления
        - xdg-desktop-portal-hyprland
        
        # Замена старых sway-утилит на новые (поддерживают эффекты)
        - hyprlock            # Экран блокировки
        - hypridle            # Авто-сон

        # --- ЗАВИСИМОСТИ ДЛЯ HUES-AI И СКРИПТОВ (ВАЖНО!) ---
        - gum                 # Рисует меню и диалоги (нужен для hues-ai)
        - jq                  # Обработка JSON (нужен для скриптов)
        - libnotify           # Команда notify-send (для уведомлений от скриптов)
        - wl-clipboard        # Работа с буфером обмена
        - cliphist            # История буфера (берется из copr)
        
        # --- ИНСТРУМЕНТЫ ---
        - grim                # Скриншоты
        - slurp               # Выделение области
        - udiskie             # Авто-монтирование флешек
        - polkit-gnome        # Окно ввода пароля (GUI)
        - nwg-look            # Настройка GTK тем
        - qt5ct               # Настройка QT тем
        - qt6ct
        
        # --- ТЕРМИНАЛЬНЫЕ УТИЛИТЫ ---
        - fastfetch           # Красивое инфо о системе (для hues-startup)
        - bat                 # cat с подсветкой
        - zoxide              # умный cd
        - topgrade            # Обновление всей системы одной командой
        - ripgrep             # Быстрый поиск текста
        - kitty               # Терминал (лучше, чем Konsole для Hyprland)

  # 6. Приложения Flatpak
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # --- ИГРЫ ---
          - com.valvesoftware.Steam
          - net.lutris.Lutris
          - com.heroicgameslauncher.hgl
          - com.usebottles.bottles
          
          # --- ОБЩЕНИЕ ---
          - dev.vencord.Vesktop
          - org.telegram.desktop
          
          # --- МЕДИА ---
          - io.mpv.Mpv
          - org.kde.haruna
          - com.obsproject.Studio
          - org.kde.gwenview
          
          # --- БРАУЗЕРЫ ---
          - com.brave.Browser
          - com.microsoft.Edge
          - org.mozilla.firefox
          
          # --- СИСТЕМА ---
          - com.github.tchx84.Flatseal
          - org.kde.ark
          - org.kde.filelight
          - io.github.flattool.Warehouse
          - io.github.mkiol.BoxBuddy  # Удобное управление контейнерами
