# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: hues-os
description: HUES-OS v1.2 - Stable Fedora 41 + Hyprland + AI Core
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 41

modules:
  # 1. Копируем файлы (твои скрипты hues-ai и конфиги)
  - type: files
    files:
      - source: system
        destination: /

  # 2. Устанавливаем Just (RPM Fusion нужно включать вручную после установки)
  - type: dnf
    install:
      packages:
        - just

  # 3. Включаем COPR репозитории (только рабочий)
  - type: script
    snippets:
      - dnf -y copr enable solopasha/hyprland || true

  # 4. Шрифты
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono

  # 5. Установка пакетов с пропуском недоступных
  - type: dnf
    install:
      packages:
        # --- HYPRLAND CORE ---
        - hyprland
        - waybar
        - wofi
        - swaybg
        - mako
        - xdg-desktop-portal-hyprland
        - hyprlock
        - hypridle

        # --- ЗАВИСИМОСТИ ДЛЯ СКРИПТОВ ---
        - gum
        - jq
        - libnotify
        - wl-clipboard
        - cliphist
        
        # --- ИНСТРУМЕНТЫ ---
        - grim
        - slurp
        - udiskie
        - polkit-gnome-authentication-agent-1
        - nwg-look
        - qt5ct
        - qt6ct
        
        # --- CLI ---
        - fastfetch
        - bat
        - zoxide
        - ripgrep
        - kitty
      options:
        - --skip-unavailable

  # 6. Установка Topgrade и Ollama через скрипты
  - type: script
    snippets:
      # Установка Topgrade
      - curl -L https://github.com/topgrade-rs/topgrade/releases/latest/download/topgrade-x86_64-unknown-linux-gnu.tar.gz -o /tmp/topgrade.tar.gz
      - tar xzf /tmp/topgrade.tar.gz -C /tmp
      - mkdir -p /usr/local/bin
      - mv /tmp/topgrade /usr/local/bin/
      - chmod +x /usr/local/bin/topgrade
      - rm -f /tmp/topgrade.tar.gz
      
      # Установка Ollama
      - curl -fsSL https://ollama.com/install.sh -o /tmp/install-ollama.sh
      - chmod +x /tmp/install-ollama.sh
      - /tmp/install-ollama.sh
      - rm -f /tmp/install-ollama.sh

  # 7. Flatpak приложения
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.valvesoftware.Steam
          - net.lutris.Lutris
          - com.heroicgameslauncher.hgl
          - com.usebottles.bottles
          - dev.vencord.Vesktop
          - org.telegram.desktop
          - io.mpv.Mpv
          - org.kde.haruna
          - com.obsproject.Studio
          - org.kde.gwenview
          - com.brave.Browser
          - com.microsoft.Edge
          - org.mozilla.firefox
          - com.github.tchx84.Flatseal
          - org.kde.ark
          - org.kde.filelight
          - io.github.flattool.Warehouse
          - io.github.mkiol.BoxBuddy

  # 8. ФИНАЛЬНЫЙ ШТРИХ: Делаем скрипты исполняемыми
  - type: script
    snippets:
      - find /usr/bin -name "hues-*" -exec chmod +x {} \;
